<?php $order = $block->getOrder(); ?>
<?php $orderData = $order->getData(); ?> 
<?php $bankList = $block->getBankList(); ?>

<?php if($block->isBankTransfer() && empty(!$block->getBankList())): ?>
		<div class="bank-transfer-list">
			<h4>Please do your payment to our Bank Account below:</h4>
			<strong>
				<?php echo $block->escapeHtml(__('Amount : ')); ?>
				<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($orderData['grand_total'],true,false); ?>
			</strong><br/><br/>
			<?php foreach ($bankList as $m) : ?>
				<div class="bank-list">
					<p><?php echo $m['bankname']; ?></p>
					<p>Bank Number</p>
					<strong><p><?php echo $m['banknumber']; ?></p></strong>
					<p>a.n. <?php echo $m['placeholder']; ?></p>
				</div>
			<?php endforeach; ?>
		</div>
<?php endif; ?>