<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php
$helper      = $this->helper('Lof\LazyLoad\Helper\Data');
$loadingIcon = $helper->getConfig('general/loadingIcon');
$imgSrc      = $helper->getMediaUrl() . 'lof/lazyload/' . $loadingIcon;
?>
<span class="product-image-container"
      style="width:<?php /* @escapeNotVerified */ echo $block->getWidth()?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php /* @escapeNotVerified */ echo ($block->getRatio() * 100); ?>%;">
        <?php if ($helper->isEnable()) { ?>
        <img class="lof-lazy product-image-photo"
             <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
             src="<?php echo $imgSrc ?>"
             data-src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
             width="<?php /* @escapeNotVerified */ echo $block->getResizedImageWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getResizedImageHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"/>
        <noscript><img class="lof-lazy product-image-photo"
             <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
             src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
             width="<?php /* @escapeNotVerified */ echo $block->getResizedImageWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getResizedImageHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"/></noscript>

        <?php } else { ?>
         <img class="product-image-photo"
             <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
             src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
             width="<?php /* @escapeNotVerified */ echo $block->getResizedImageWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getResizedImageHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"/>
        <?php } ?>
    </span>
</span>
