<?php /** @var $block \Jajuma\WebpImages\Block\Product\Image */ ?>
<?php 
    $imageUrl = $block->getImageUrl();
?>
<span class="product-image-container"
      style="width:<?= $block->escapeHtmlAttr($block->getWidth()) ?>px;">
    <span class="product-image-wrapper" style="padding-bottom: <?= ($block->getRatio() * 100) ?>%;">

    <picture>
        <source type="image/webp" srcset="<?= $imageUrl ?>">
        <source type="image/png" srcset="<?= $block->getOrigImageUrl() ?>">
        <img class="<?= $block->escapeHtmlAttr($block->getClass()) ?>"
            <?= $block->escapeHtmlAttr($block->getCustomAttributes()) ?>
            src="<?= $block->escapeUrl($block->getOrigImageUrl()) ?>"
            max-width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
            max-height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"
            alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>"/>
    </picture>


    </span>
</span>
