<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="maintenance">
</div>
<style type="text/css">
	body,html{
		height: 100%;
	}
	.page-main {
		padding: 0;
	    height: 100%;
		background:url("../../media/wysiwyg/maintenance.png");
	    background-size: 100% auto;
	}
	@media screen and (max-width: 768px) {
	  .page-main {
	  	background-size: auto 100%;
	    background-position: center center;
	  }
	}
</style>
