<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="maintenance">
	<img class="swift-logo" src="../default/images/swift-logo.png">
	<div class="container">
		<img class="truck" src="../default/images/truck.png">
		<div class="text">
			<p>We’re working to make our website better than ever.</p>
			<p>Check back in a bit. We’ll see you soon.</p>
		</div>
	</div>
</div>