<?php
$_helper = $this->helper('WeltPixel\ProductPage\Helper\Data');
$isMagnifierEnabled = $_helper->getMagnifierEnabled();
$zoomType = $_helper->getMagnifierEventType();
?>

<?php if ($isMagnifierEnabled && $zoomType == 'hover') : ?>

<script>
    require(["jquery"], function ($) {
        $(document).ready(function() {
            $(document).on('mouseleave', '.fotorama__stage' ,function() {
                $('.magnify-lens').addClass('magnify-hidden');
                $('.magnifier-preview').addClass('magnify-hidden');
            });
        });
    });
    require(['jquery', 'mage/gallery/gallery'], function($, gallery){
        $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {
            $(this).on('fotorama:ready', function() {
                if ($('.fotorama__nav-wrap--vertical')) {
                    $('.fotorama__stage').width( $('.fotorama__stage').width() - $('.fotorama__nav-wrap--vertical').width() - 5);
                }
            });
        });
    });
</script>
<?php endif; ?>