FROM asia.gcr.io/sirclo-iii-nonprod/mgt-swift81:a3ac0110cc9117443a3b934f4851dae801e11fd3-1664161649

ARG DEBIAN_FRONTEND=noninteractive
ARG php_version="8.1"
ARG dir_composer="/home/app/site/vendor"
ARG dst_mnt="/home/app/site/pub/errors/default"

# Entrypoint
COPY start.sh /start.sh
RUN chmod +x /start.sh;

# Change to home apps
WORKDIR /home/app/
COPY --chown=app:app . site
COPY --chown=app:app global_patch.sh /home/app/site/global_patch.sh

#change to root directory
WORKDIR /home/app/site
USER app

# Composer process
RUN composer install --prefer-dist

# Start line patch
RUN sh global_patch.sh
USER root
