FROM asia.gcr.io/sirclo-iii-nonprod/mgt-swift74:91f85256742729071555efb9ca445b026808e9e3-1656037500

ARG DEBIAN_FRONTEND=noninteractive
ARG php_version="7.4"
ARG dir_composer="/home/app/site/vendor"
ARG dst_mnt="/home/app/site/pub/errors/default"

# Entrypoint
COPY start.sh /start.sh
RUN chmod +x /start.sh;

# Change to home apps
WORKDIR /home/app/
COPY --chown=app:app . site
COPY --chown=app:app global_patch.sh /home/app/site/global_patch.sh

#change to root directory
WORKDIR /home/app/site
USER app

# Composer process
RUN composer global require hirak/prestissimo && \
    composer install --prefer-dist

# Start line patch
RUN sh global_patch.sh
USER root
