FROM asia.gcr.io/sirclo-iii-nonprod/mgt-swift74:c52175d308111be67924b5b425ae0a9a5c275a69-1635222100

ARG DEBIAN_FRONTEND=noninteractive
ARG php_version="7.4"
ARG dir_composer="/home/app/site/vendor"
ARG dst_mnt="/home/app/site/pub/errors/default"

# Entrypoint
COPY start.sh /start.sh
RUN chmod +x /start.sh;

# Change to home apps
WORKDIR /home/app/
COPY --chown=app:app . site
COPY --chown=app:app .servcomp/env.php /home/app/site/app/etc/env.php
COPY --chown=app:app .servcomp/.my.cnf /home/app/.my.cnf

WORKDIR /home/app/site
USER app
RUN composer config repositories.icubeus-customkaycollection git git@github.com:icube-mage/magento2-customkaycollection.git
RUN composer require icubeus/magento2-customkaycollection:dev-master  -vvv
#RUN rm -rf generated/; \
#    rm -rf var/cache var/composer_home var/di  var/page_cache var/session var/tmp var/view_preprocessed var/cache/ pub/static/frontend/* pub/static/_cache/generated/; \
#    php bin/magento setup:upgrade; \
#    php bin/magento setup:di:compile; \
#    php bin/magento weltpixel:less:generate; \
#    php -dmemory_limt=-1 bin/magento setup:static-content:deploy id_ID en_US -f; \
#    php bin/magento weltpixel:css:generate --store=default; \
#    php bin/magento cache:flush;\ 

USER root
EXPOSE 80 8080 9000 6082
ENTRYPOINT /start.sh
