<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Blog\Block\Widget\RecentPost */

// @codingStandardsIgnoreFile
$canShow = true;
if (!$block->isAjax()): ?>
    <?php $canShow = false; ?>
    <div data-aw-blog-block-name="<?php /* @noEscape */ echo $block->getWidgetEncodeData() ?>"></div>
<?php endif; ?>

<?php if ($canShow && $block->isEnabled()): ?>
    <?php
        $recentPosts = $block->getPosts();
        $title = $block->getTitle() ? : 'Recent Posts';
    ?>
    <?php if (count($recentPosts)): ?>
        <div class="block widget block-blog-recent-post">
            <div class="block-title">
                <strong><?php echo __($block->escapeHtml($title)) ?></strong>
            </div>
            <div class="block-content">
                <div class="block-recent-posts">
                    <?php foreach ($recentPosts as $post): ?>
                        <li class="block-recent-posts-item">
                            <a href="<?php /* @noEscape */ echo $block->getPostUrl($post) ?>"
                               class="block-recent-posts-link">
                                <?php echo $block->escapeHtml($post->getTitle()) ?>
                            </a>
							<?php if($post->getFeaturedImageFile()):?>
							<img class="blog-post-featured-image"
			                     src = "<?php /* @noEscape */ echo $block->escapeXssInUrl($block->getFeaturedImageUrl($post->getFeaturedImageFile())) ?>"
			                     title = "<?php echo $block->escapeHtml($post->getTitle()) ?>"
			                     alt = "<?php echo $block->escapeHtml($post->getTitle()) ?>"
							                />
							<?php endif;?>
                        </li>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
