<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<h2>
    <span><?php /* @escapeNotVerified */ echo __('WeltPixel Cache Management') ?></span>
</h2>
<p>
    <button onclick="setLocation('<?php /* @escapeNotVerified */ echo $block->getCleanLessUrl() ?>')" type="button">
        <?php /* @escapeNotVerified */ echo __('Regenerate Pearl Theme Less') ?>
    </button>
    <span><?php /* @escapeNotVerified */ echo __('Regenerate the less files based on the latest changes') ?></span>
</p>
