<li data-bind="scope: 'customer'">
<!-- ko ifnot: customer().fullname  -->
    <a href="<?php echo $this->getUrl('customer/account/create/'); ?>"><?php echo __('Create an Account') ?></a>
<!-- /ko -->
</li>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>