<table class="email-items">
    <thead>
        <tr>
            <th class="item-info">
                <?= /* @escapeNotVerified */  __('No'); ?>
            </th>
            <th class="item-qty">
                <?= /* @escapeNotVerified */  __('SKU'); ?>
            </th>
            <th class="item-price">
                <?= /* @escapeNotVerified */  __('Nama Brang'); ?>
            </th>
            <th class="item-price">
                <?= /* @escapeNotVerified */  __('Harga'); ?>
            </th>
            <th class="item-price">
                <?= /* @escapeNotVerified */  __('Jumlah'); ?>
            </th>
             <th class="item-price">
                <?= /* @escapeNotVerified */  __('Sub Total'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <!-- <?php foreach ($_items as $_item): ?>
        <tr>
            <td>$item->getName()</td>
            <td>$item->getSku()</td>
            <td>$item->getPrice()</td>
        </tr>
    <?php endforeach; ?> -->
    </tbody>
</table>