<?php
/* @var $block \Aheadworks\Blog\Block\Adminhtml\Post\Edit\Tab\Renderer\Category */
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note">' . $element->getNote() . '</div>' : '';

/*$elementBeforeLabel = $element->getExtType() == 'checkbox' || $element->getExtType() == 'radio';
$addOn = $element->getBeforeElementHtml() || $element->getAfterElementHtml();*/


$fieldId = ($element->getHtmlId()) ? ' id="attribute-' . $element->getHtmlId() . '-container"' : '';
$fieldClass = "field field-{$element->getId()} {$element->getCssClass()}";
//$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ' with-addon';
$fieldClass .= ($element->getRequired()) ? ' required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId());
?>
<?php if (!$element->getNoDisplay()): ?>
    <div<?php echo $fieldAttributes ?> data-attribute-code="<?php echo $element->getHtmlId() ?>"
                                       data-apply-to="<?php echo $block->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode([]))?>"
    >
        <?php echo $element->getLabelHtml() ?>
        <div class="control">
            <div class="addon">
                <?php echo $element->getElementHtml() ?>
                <?php $suggestElementId = $element->getHtmlId() . '-suggest'; ?>
                <input id="<?php echo $suggestElementId ?>" placeholder="<?php echo __('start typing to search category'); ?>" />
                <script>
                    require(["jquery", "mage/mage"], function($){
                        $("#<?php echo $suggestElementId ?>").mage(
                            'treeSuggest',
                            <?php echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getSelectorOptions()) ?>
                        );
                    });
                </script>
                <?php echo $block->getNewBtnHtml() ?>
                <?php echo $note ?>
            </div>
        </div>
    </div>
<?php endif; ?>
