<?php 
$customerId =  $this->getCustomerId();

echo $this->scopeConfig->getValue('prism/widget_snippet/script',\Magento\Store\Model\ScopeInterface::SCOPE_STORE);

?>
<style type="text/css">
    .sfe-attention-grabber__text-span {
        border: none !important;
        background-color: #f0e6d8 !important; // attention grabber background
    }
    .sfe-attention-grabber__text-span > .sfe-attention-grabber__text-span--desktop,
    .sfe-attention-grabber__text-span > .sfe-attention-grabber__text-span--mobile {
        color: #8c363c; // attention grabber text color
    }
</style>