<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Extrafee
 */
?>
<?php /** @var \Magento\Backend\Block\Template $block */ ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Amasty_Extrafee/js/order/order-form-extend": {
                "configureProductToAdd": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('sales/order_create/configureProductToAdd'))) ?>",
                "configureQuoteItems":  "<?= $block->escapeJs($block->escapeUrl($block->getUrl('sales/order_create/configureQuoteItems'))) ?>"
            }
        }
    }
</script>
