<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<h2>
    <span><?php /* @escapeNotVerified */ echo __('Icube Bundle') ?></span>
</h2>
<form id="generate-js-bundle" action="<?php /* @escapeNotVerified */ echo $block->getJsBundleGeneratgionUrl() ?>" method="POST" >
	<p>
	    <input type="hidden" value="<?php echo $block->getFormKey(); ?>" name="form_key" id="form_key" />
	    
	    <button id="regenerate-jsbundle-button" type="submit">
	        <?php /* @escapeNotVerified */ echo __('Regenerate JS bundle') ?>
	    </button>
    </p>
</form>
