<div class="block block-gosend-details-view">
    <div class="block-title">
        <strong>Shipping Info</strong>
    </div>
    <div class="block-content">
        <div class="box box-gosend-status">
            <strong class="box-title"><span>Gosend Status</span></strong>
            <div class="box-content">
                Picked
            </div>
        </div>

        <div class="box box-gosend-booking-number">
            <strong class="box-title">
                <span>Booking Number</span>
            </strong>
            <div class="box-content">
                GK-228221408 </div>
        </div>

        <div class="box box-gosend-driver">
            <strong class="box-title">
                <span>Driver</span>
            </strong>
            <div class="box-content">
                Danu Kuntoyo<br />
                <a href="tel:+6287777785644">+6287777785644</a>
            </div>
        </div>
        <div class="box box-gosend-booking-type">
            <strong class="box-title">
                <span>Booking Type</span>
            </strong>
            <div class="box-content">
                Same Day
            </div>
        </div>
        <div class="box box-gosend-store-address">
            <strong class="box-title"><span>Store Address</span></strong>
            <div class="box-content">
                <address>
                    PetStore Name<br />
                    Pondok Indah Office Tower 3, lt. 8<br />
                    Jl. Sultan Iskandar Muda Kav. V-TA, Pondok Indah<br />
                    Jakarta Selatan 12310 Indonesia<br />
                    <a href="tel:+622129327950">+622129327950</a>
                </address>
            </div>
        </div>
        <button type="submit" title="Live Tracking" class="action tracking primary">
            <span>Live Tracking</span>
        </button>
    </div>
</div>