<?php
    $status = $block->getOrder()->getStatusLabel();
?>

<ul class="opc-progress-bar">
<li class="opc-progress-bar-item pending <?php if($status=='Pending') {?> _active<?php } else {?> _complete<?php }?>">
            <span>Waiting for Confirmation</span>
        </li>
    
        <li class="opc-progress-bar-item processing <?php if($status=='Processing') {?> _active<?php } else if ($status=='Shipped' || $status=='Complete' || $status=='Canceled') {?> _complete<?php }?>">
        <?php if($status=='Processing') {?>
        <span>Processing</span>
        <?php } else if($status=='Canceled'){?>
        <span>Order Canceled</span>
        <?php } ?>
        </li>
    
    <li class="opc-progress-bar-item ship <?php if($status=='Shipped') {?> _active<?php }  else if ($status=='Complete') {?> _complete<?php }?>">
            <span>Shipped</span>
        </li>

    <li class="opc-progress-bar-item completed <?php if($status=='Complete') {?> _active<?php } ?>">
            <span>Order Complete</span>
        </li>
</ul>