<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Ogrid
 */

namespace Amasty\Ogrid\Ui\Component\Listing\Column;


use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;

class Track extends \Magento\Ui\Component\Listing\Columns\Column
{
    protected $helper;

    /**
     * @param ContextInterface $context
     * @param UiComponentFactory $uiComponentFactory
     * @param \Magento\Shipping\Helper\Data $helper
     * @param array $components
     * @param array $data
     */
    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        \Magento\Framework\Url\EncoderInterface $urlEncoder,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        array $components = [],
        array $data = []
    )
    {
        $this->urlEncoder = $urlEncoder;
        $this->storeManager = $storeManager;
        parent::__construct($context, $uiComponentFactory, $components, $data); // TODO: Change the autogenerated stub
    }

    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as & $item) {
                if (array_key_exists('amasty_ogrid_sales_shipment_track', $item)){
                    $urlPart = "order_id:{$item['entity_id']}:{$item['amasty_ogrid_sales_order_protect_code']}";
                    $params = [
                        '_direct' => 'shipping/tracking/popup',
                        '_query' => ['hash' => $this->urlEncoder->encode($urlPart)]
                    ];

                    $storeModel = $this->storeManager->getStore($item['amasty_ogrid_sales_order_store_id']);

                    $item['amasty_ogrid_sales_shipment_track'] = implode('<br/>', $item['amasty_ogrid_sales_shipment_track']) .
                    '<br/><a href="#" onclick="popWin(\'' .
                        $storeModel->getUrl('', $params) .
                        '\',\'trackorder\',\'width=800,height=600,resizable=yes,scrollbars=yes\'); event.stopPropagation(); return false;">' .
                        __('Track Order') .
                    '</a>';
                }
            }
        }
        return $dataSource;
    }
}