<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image"
     <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
     src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
    <?php if ($block->getHoverImageUrl()) :  ?>
     data-hoversrc="<?php /* @escapeNotVerified */ echo $block->getHoverImageUrl(); ?>"
     onmouseover="tmpSrc = this.src; this.src=this.getAttribute('data-hoversrc'); this.setAttribute('data-hoversrc', tmpSrc);"
     onmouseout=onmouseover()
     <?php endif; ?>
     width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
     height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>" />
