<?php
    $path = $this->getRequest()->getParam('path');

    if (!isset($path) || $path === '') {
        $path = $block->getPath();
    }

    if (!isset($path) || $path === '') {
        $path = '/login';
    }

    if (!strrpos($path, 'accessToken')) {
        if (strrpos($path, '?') > -1) {
            $path .= '&';
        } else {
            $path .= '?';
        }
        $path .= 'accessToken='.$this->configHelper->getAccessToken();
    }

    $url = $block->configHelper->getWebsiteBaseUrl().$path;
?>

<div id="ns8-modal" style="display: none"></div>

<!--  Message handlers for message from the IFRAME  -->
<script src="<?= $block->configHelper->getWebsiteBaseUrl().'/js/admin.js' ?>"></script>

<!--  The IFRAME that hosts the app  -->
<iframe id="ns8-app-iframe" frameborder="0" scrolling="no" src="<?= $url ?>"></iframe>

<script type="text/javascript">
    var NS8CSPContainer = {
        cancelUrl: '<?php echo $block->escapeUrl($this->configHelper->getAdminUrl("ns8cspadmin/ajax/cancel")) ?>',
        orderViewUrl: '<?php echo $block->
            escapeUrl($this->configHelper->getAdminUrl("sales/order/view", [ "order_id" => "{{id}}" ])) ?>',
        orderViewByIncrementIdUrl: '<?php echo $block->
            escapeUrl($this->configHelper->
            getAdminUrl("ns8cspadmin/redirect/orderbyincrementid", ["increment_id" => "{{increment_id}}"])) ?>',
        approveUrl: '<?php echo $block->escapeUrl($this->configHelper->getAdminUrl("ns8cspadmin/ajax/approve")) ?>',
        holdUrl: '<?php echo $block->escapeUrl($this->configHelper->getAdminUrl("ns8cspadmin/ajax/hold")) ?>',
        validateUrl: '<?php echo $block->escapeUrl($this->configHelper->getAdminUrl("ns8cspadmin/ajax/validate")) ?>'
    };

    require(
        [ 'jquery' ],
        function($) {
            $(function() {
                initializeAdmin($);
            });
        }
    );
</script>

