<div id="category-edit-tree">
<div class="categories-side-col">
    <div class="sidebar-actions">
        <?php if ($block->getRoot()): ?>
            <?php echo $block->getAddRootButtonHtml() ?><br/>
            <?php echo $block->getAddSubButtonHtml() ?>
        <?php endif; ?>
    </div>
    <div class="tree-actions">
        <?php if ($block->getRoot()): ?>
        <a href="#" onclick="jQuery('[data-role=tree]').jstree('close_all');"><?php echo __('Collapse All'); ?></a>
        <span class="separator">|</span> <a href="#" onclick="jQuery('[data-role=tree]').jstree('open_all');"><?php echo __('Expand All'); ?></a>
        <?php endif; ?>
    </div>
<?php if ($block->getRoot()): ?>
    <div class="tree-holder">
        <div data-role="tree" data-mage-init='<?php echo $block->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getTreeWidgetOptions())); ?>'>
        </div>
    </div>
</div>

<div data-id="information-dialog-tree" class="messages" style="display: none;">
    <div class="message message-notice">
       <div><?php echo __('This operation can take a long time'); ?></div>
    </div>
</div>
<?php endif; ?>
</div>