<?php
// @codingStandardsIgnoreFile

/** @var \Aheadworks\AdvancedReports\Block\Adminhtml\View\IndexInfo $block */
?>
<div class="messages">
    <div class="aw-ar__message-wrapper" data-role="aw-ar-message" data-bind="scope: 'dateNotify'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div class="message message-notice notice">
        <div data-ui-id="messages-message-notice">
            <?php echo $block->escapeHtml($block->showLastIndexUpdate()) ?>
            <?php if($block->canShowScheduleMessage()): ?>
                <?php echo $block->escapeHtml(__('To schedule Advanced Reports index update click')); ?>
                <a href="<?php echo $block->escapeUrl($block->getIndexUpdateUrl()); ?>">
                    <?php echo $block->escapeHtml(__('here')) ?>
                </a>
            <?php endif; ?>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "dateNotify": {
                        "component": "Aheadworks_AdvancedReports/js/ui/messages/date-notify"
                    }
                }
            }
        }
    }
    </script>
</div>
