<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

// @codingStandardsIgnoreFile

/** @var \Aheadworks\AdvancedReports\Block\Adminhtml\View\Period $block */
$period = $block->getPeriod();
$from = $period['from'];
$to = $period['to'];
$comparePeriod = $block->getComparePeriod();
$compareEnabled = $comparePeriod['enabled'];
$compareFrom = $comparePeriod['from'];
$compareTo = $comparePeriod['to'];
?>
<div id="awarep-calendars-box">
    <div id="awarep-calendars_header">
        <?php /* @noEscape */ echo $from->format('M d, Y') ?> &nbsp;-&nbsp; <?php /* @noEscape */ echo $to->format('M d, Y') ?>
    </div>
    <div id="awarep-calendars_header_compare"></div>
    <div id="awarep-calendars-container">
        <div id="awarep-calendars"></div>
        <div id="awarep-calendar_form">
            <div class="awarep-date_range_box">
                <span><?php echo $block->escapeHtml(__('Date Range')) ?>:</span>
                <select class="input-text no-changes advanced-filter"
                        name="custom_date_range"
                        id="awarep-custom_date_range">
                    <?php foreach ($block->getOptions() as $option): ?>
                        <option value="<?php /* @noEscape */ echo $option['value'] ?>"
                            <?php /* @noEscape */ echo ($option['value'] == $period['type']) ? 'selected' : '' ?>>
                            <?php echo $block->escapeHtml(__($option['label'])) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div id="awarep-fields">
                <span class="awarep-period_field">
                    <div class="element_outer_border">
                        <input type="text" name="report_from" value="<?php /* @noEscape */ echo $from->format('M d, Y') ?>"
                               id="awarep-period_date_from" />
                    </div>
                </span>
                <span>&nbsp;-&nbsp;</span>
                <span class="awarep-period_field">
                    <div class="element_outer_border">
                        <input type="text" name="report_to" value="<?php /* @noEscape */ echo $to->format('M d, Y') ?>"
                               id="awarep-period_date_to" />
                    </div>
                </span>
                <div class="awarep-compare_range_box">
                    <span>
                        <input type="checkbox" name="compare_checkbox" id='awarep-compare_checkbox' value="Compare" disabled>
                    </span>
                    <span><?php echo $block->escapeHtml(__('Compare to')) ?>:</span>
                    <select class="input-text no-changes advanced-filter"
                            name="compare_dropdown_date_range"
                            id="awarep-compare_dropdown_date_range" disabled>
                        <?php foreach ($block->getCompareOptions() as $option): ?>
                            <option value="<?php /* @noEscape */ echo $option['value'] ?>"
                                <?php if ($compareEnabled) : ?>
                                    <?php /* @noEscape */ echo ($option['value'] == $comparePeriod['type']) ? 'selected' : '' ?>>
                                <?php else : ?>
                                    <?php /* @noEscape */ echo ($option['value'] == $comparePeriod['default_type']) ? 'selected' : '' ?>>
                                <?php endif ?>
                                <?php echo $block->escapeHtml(__($option['label'])) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <span id="awarep-compare_custom_date_range" style="display: none">
                    <span class="awarep-period_field">
                        <div class="element_outer_border">
                            <input type="text" name="compare_from" value="<?php /* @noEscape */ if ($block->isCompareAvailable()) { echo $compareFrom->format('M d, Y'); } ?>"
                                id="awarep-compare_date_from" />
                        </div>
                    </span>
                    <span>&nbsp;-&nbsp;</span>
                    <span class="awarep-period_field">
                        <div class="element_outer_border">
                            <input type="text" name="compare_from_to" value="<?php /* @noEscape */ if ($block->isCompareAvailable()) { echo $compareTo->format('M d, Y'); } ?>"
                               id="awarep-compare_date_to" />
                        </div>
                    </span>
                </span>
            </div>
            <div class="awarep-button-set">
                <button type="button" class="scalable task" id="awarep-apply-period">
                    <span><?php echo $block->escapeHtml(__('Apply')) ?></span>
                </button>
                <button type="button" class="awarep-hide-calendar-button scalable task" id="awarep-cancel-period">
                    <span><?php echo $block->escapeHtml(__('Cancel')) ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#awarep-calendars-box": {
            "awArepPeriod": {
                "earliest": <?php /* @noEscape */ echo \Zend_Json::encode($block->getEarliestCalendarDateAsString()) ?>,
                "latest": <?php /* @noEscape */ echo \Zend_Json::encode($block->getLatestCalendarDateAsString()) ?>,
                "weekOffset": <?php /* @noEscape */ echo $block->getFirstDayOfWeek() ?>,
                "ranges": <?php /* @noEscape */ echo \Zend_Json::encode($block->getRanges()) ?>,
                "compareAvailable": <?php /* @noEscape */ echo \Zend_Json::encode($block->isCompareAvailable()) ?>,
                "compareEnabled": <?php /* @noEscape */ echo \Zend_Json::encode($comparePeriod['enabled']) ?>,
                "compareTypeDefault": <?php /* @noEscape */ echo \Zend_Json::encode($comparePeriod['default_type']) ?>
            }
        }
    }
</script>