<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

// @codingStandardsIgnoreFile

/** @var \Aheadworks\AdvancedReports\Block\Adminhtml\View\Store $block */
?>
<div class="aw-arep-store aw-menu">
    <div class="actions dropdown closable">
        <button type="button"
                class="admin__action-dropdown"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                aria-haspopup="true">
            <span class="admin__action-dropdown-text">
                <?php echo $block->escapeHtml(__($block->getCurrentItemTitle())) ?>
            </span>
        </button>
        <ul class="dropdown-menu">
            <?php foreach($block->getItems() as $key => $item): ?>
                <?php $class = 'aw-arep-store__dropdown-menu-action--' .  $item['type'] .
                    ($key == $block->getCurrentItemKey() ? ' current' : '')
                ?>
                <li class="<?php /* @noEscape */ echo $class ?>">
                    <?php $disabled = isset($item['disabled']) && $item['disabled'] ?>
                    <a class="<?php /* @noEscape */ echo $disabled ? 'disabled' : '' ?>"
                       href="<?php /* @noEscape */ echo $disabled ? '' : $block->escapeXssInUrl($item['url']) ?>">
                        <?php echo $block->escapeHtml($item['title']) ?>
                    </a>
                </li>
            <?php endforeach;?>
        </ul>
    </div>
</div>
