<div id="<?php echo $block->getNameInLayout() ?>" style="display:none">
    <?php echo $block->getFormHtml();?>
    <script>
        require(['jquery','mage/mage', 'Aheadworks_Blog/js/category/new-dialog'],function($) {
            $(function(){
                var catNewForm = $('#<?php echo $block->getNameInLayout() ?>');
                $.awblog.newCategoryDialog(
                    <?php echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWidgetOptions()) ?>,
                    catNewForm
                );
            });
        });
    </script>
</div>
