<?php

// @codingStandardsIgnoreFile
/** @var \Icube\CustomStyle\Block\Cache\Permissions|null $permissions */
$permissions = $block->getData('custompermissions');
?>
<br/>
<?php if ($permissions && $permissions->hasAccessToClearPageCache()): ?>
<form id="clear-page" action="<?php /* @escapeNotVerified */ echo $block->getClearPageUrl() ?>" method="POST" >
    <input type="hidden" value="<?php echo $block->getFormKey(); ?>" name="form_key" id="form_key" />
    
    <button id="clear-page-button" type="submit">
        <?php /* @escapeNotVerified */ echo __('Clear Page Cache') ?>
    </button>
</form>
<?php endif; ?>
