<?php

// @codingStandardsIgnoreFile
/** @var \Icube\CustomStyle\Block\Cache\Permissions|null $permissions */
$permissions = $block->getData('custompermissions');
?>
<br/>
<?php if ($permissions && $permissions->hasAccessToReneregateStatic()): ?>
<form id="content-deploy" action="<?php /* @escapeNotVerified */ echo $block->getDeployUrl() ?>" method="POST" >
    <input type="hidden" value="<?php echo $block->getFormKey(); ?>" name="form_key" id="form_key" />
    
    <button id="content-deploy-button" type="submit">
        <?php /* @escapeNotVerified */ echo __('Regenerated static files') ?>
    </button>
</form>
<?php endif; ?>

