<?php

// @codingStandardsIgnoreFile
/** @var \Icube\CustomStyle\Block\Cache\Permissions|null $permissions */
$permissions = $block->getData('custompermissions');
?>
<?php if ($permissions && $permissions->hasAccessToClearVarnish()): ?>
<form id="clear-varnish" action="<?php /* @escapeNotVerified */ echo $block->getVarnishGenerationUrl() ?>" method="POST" >
    <input type="hidden" value="<?php echo $block->getFormKey(); ?>" name="form_key" id="form_key" />
    
    <button id="clear-varnish-button" type="submit">
        <?php /* @escapeNotVerified */ echo __('Clear Varnish Cache') ?>
    </button>
</form>
<br/>
<?php endif; ?>