<?php
    $parentId = $block->getParentCategoryId();
    $categoryId = $block->getCategoryId();
?>
<div class="category-edit-title">
    <h3 class="title"><?php echo $block->escapeHtml($block->getHeader()) . ($categoryId ? ' (' . __('ID: %1', $categoryId) . ')' : '') ?></h3>
</div>
<div data-mage-init='{"floatingHeader": {}}' class="page-actions">
    <?php echo $block->getPageActionsHtml() ?>
</div>
    <?php echo $block->getTabsHtml() ?>
<iframe name="iframeSave" style="display:none; width:100%;"
        src="<?php echo $block->getViewFileUrl('blank.html') ?>"></iframe>
<form id="category_edit_form" name="category-edit-form" action="<?php echo $block->getSaveUrl() ?>" method="post"
      enctype="multipart/form-data">
    <div class="no-display">
        <input type="hidden" name="isIframe" value="1"/>
        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>"/>
        <input type="hidden" name="category_products" id="in_category_products" value=""/>
        <input type="hidden" name="active_tab_id" id="active_tab_id" value=""/>
        <?php if ($parentId !== 0): ?>
            <input type="hidden" name="parent" value="<?php echo $parentId; ?>"/>
        <?php endif; ?>
        <?php if ($categoryId !== 0): ?>
            <input type="hidden" name="id" value="<?php echo $categoryId; ?>"/>
        <?php endif; ?>
    </div>
    <div id="blog_cat_tab_content"></div>
</form>

<div data-id="information-dialog-category" class="messages" style="display: none;">
    <div class="message message-notice">
        <div><?php echo __('This operation can take a long time'); ?></div>
    </div>
</div>
<script>
    require(['jquery', 'jquery/ui', 'mage/mage', 'loadingPopup', 'Aheadworks_Blog/js/category/form'/*, "mage/translate"*/], function($){
        var catEditForm = $('#category_edit_form');
        $.awblog.categoryForm({}, catEditForm);
        catEditForm.mage('validation', {submitHandler: function(form){
            form.submit();
            $('body').loadingPopup();
        }});
    });
</script>
