var config = {
    paths: {
        Swiper: 'js/vendor/swiper',
        vendors: 'vendors',
        isMobile: 'js/vendor/ismobile',
    },
    shim: {
        isMobile: {
            exports: 'isMobile',
        },
        // Defining implicit dependency on commons package generated by Webpack
        // Every entry point that generates JavaScript should be defined here.
        'js/cms': ['js/commons'],
        'js/styleguide': ['js/commons'],
    },
};