<?php

// @codingStandardsIgnoreFile

$uniqueid = 'instagram-widget-'.uniqid();
$instagramClientId = $this->getData('instagram_client_id');
$instagramAccessToken = $this->getData('instagram_access_token');
$imagesPerRow = $this->getData('images_per_row');
$description = trim($this->getData('description'));
$backgroundColor = trim($this->getData('background_color'));
$title = trim($this->getData('title'));
$limit = intval($this->getData('limit'));
$sortBy = $this->getData('sort_by');
$resolution = $this->getData('resolution');
$feedType = $this->getData('feed_type');
$userId = $this->getData('user_id');
$tagName = $this->getData('tag_name');
$locationId = $this->getData('location_id');
?>
<div class="instagram-widget-container " <?php if ($backgroundColor) : ?> style="background-color: <?php echo $backgroundColor; ?>" <?php endif; ?>>
    <div class="instagram-heading-title center">
        <?php if ($title) :  ?>
            <h3><?php /* @escapeNotVerified */ echo $title ?></h3>
        <?php endif; ?>
        <?php if ($description) :  ?>
            <span class="center"><?php /* @escapeNotVerified */ echo $description ?></span>
        <?php endif; ?>
    </div>
    <div id="<?php echo $uniqueid; ?>" class="instagram-photos <?php /* @escapeNotVerified */ echo $imagesPerRow ?>" ></div>
</div>
<div class="clear" >&nbsp;</div>
<script>
    require(['jquery', 'Instafeed'],
        function ($, Instafeed) {
            var c_accessToken = '<?php  echo $instagramAccessToken; ?>';
            var c_clientID = '<?php echo $instagramClientId; ?>';
            var $instagramPhotosEl = $('#<?php echo $uniqueid; ?>');
            if( $instagramPhotosEl.length > 0 ){

                $instagramPhotosEl.each(function() {
                    var element = $(this),
                        instaGramTarget = element.attr('id'),
                        instaGramUserId = '<?php echo $userId ?>',
                        instaGramTag = '<?php echo $tagName ?>',
                        instaGramLocation = '<?php echo $locationId ?>',
                        instaGramCount = <?php echo $limit ?>,
                        instaGramType = '<?php echo $feedType ?>',
                        instaGramSortBy = '<?php echo $sortBy ?>',
                        instaGramRes = '<?php echo $resolution ?>';

                    if( !instaGramCount ) { instaGramCount = 9; }
                    if( !instaGramSortBy ) { instaGramSortBy = 'none'; }
                    if( !instaGramRes ) { instaGramRes = 'standard_resolution'; }
                    //low_resolution

                    if( instaGramType == 'user' ) {

                        var feed = new Instafeed({
                            target: instaGramTarget,
                            get: instaGramType,
                            userId: Number(instaGramUserId),
                            limit: Number(instaGramCount),
                            sortBy: instaGramSortBy,
                            resolution: instaGramRes,
                            accessToken: c_accessToken,
                            clientId: c_clientID
                        });

                    } else if( instaGramType == 'tagged' ) {

                        var feed = new Instafeed({
                            target: instaGramTarget,
                            get: instaGramType,
                            tagName: instaGramTag,
                            limit: Number(instaGramCount),
                            sortBy: instaGramSortBy,
                            resolution: instaGramRes,
                            accessToken: c_accessToken,
                            clientId: c_accessToken
                        });

                    } else if( instaGramType == 'location' ) {

                        var feed = new Instafeed({
                            target: instaGramTarget,
                            get: instaGramType,
                            locationId: Number(instaGramLocation),
                            limit: Number(instaGramCount),
                            sortBy: instaGramSortBy,
                            resolution: instaGramRes,
                            accessToken: c_accessToken,
                            clientId: c_accessToken
                        });

                    }

                    feed.run();
                });
            }
        });
</script>
